//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money_Tracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Id|Name|Email|Password|Type|Country")]
        public string User_Cols {
            get {
                return ((string)(this["User_Cols"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=MoneyManagenent;Integrated Security=True")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"INSERT INTO [dbo].[User]
           ([Name]
           ,[Email]
           ,[Password]
           ,[Type]
           ,[Country])
     VALUES
           (Name=@Name
           ,Email=@Email
           ,Password=@Password
           ,Type=@Type
           ,Country=@Country)")]
        public string InsertUser {
            get {
                return ((string)(this["InsertUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE [dbo].[User]\r\n   SET [Name] = @Name\r\n      ,[Email] = @Email\r\n      ,[Pass" +
            "word] = @Password\r\n      ,[Type] = @Type\r\n      ,[Country] = @Country\r\n WHERE Id" +
            "=@Id")]
        public string UpdateUser {
            get {
                return ((string)(this["UpdateUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[User]\r\n      WHERE Id=@Id")]
        public string DeleteUser {
            get {
                return ((string)(this["DeleteUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO [dbo].[Country]\r\n           ([Name]\r\n           ,[Currency])\r\n     VA" +
            "LUES\r\n           (Name=@Name\r\n           ,Currency=@Currency)")]
        public string InsertCountry {
            get {
                return ((string)(this["InsertCountry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE [dbo].[Country]\r\n   SET [Name] = @Name\r\n      ,[Currency] = @Currency\r\n WH" +
            "ERE Id=@Id")]
        public string UpdateCountry {
            get {
                return ((string)(this["UpdateCountry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[Country]\r\n      WHERE Id=@Id")]
        public string DeleteCountry {
            get {
                return ((string)(this["DeleteCountry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Id|Name|")]
        public string Country_Cols {
            get {
                return ((string)(this["Country_Cols"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User_id|Date|Expense|Income|Balance")]
        public string Balance_cols {
            get {
                return ((string)(this["Balance_cols"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InsertBalance {
            get {
                return ((string)(this["InsertBalance"]));
            }
        }
    }
}
